# Generated by Django 4.2.7 on 2023-12-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('name', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.TextField(blank=True, max_length=40)),
                ('rollNumber', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('department', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('cnic', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('MobileNo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionCattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdata')),
            ],
            options={
                'unique_together': {('rollno', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectionC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtype', models.CharField(blank=True, max_length=30, null=True)),
                ('English', models.IntegerField(default=0)),
                ('Maths', models.IntegerField(default=0)),
                ('Urdu', models.IntegerField(default=0)),
                ('ComputerScience', models.IntegerField(default=0)),
                ('SocialStudies', models.IntegerField(default=0)),
                ('Physics', models.IntegerField(default=0)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdata')),
            ],
            options={
                'unique_together': {('rollno', 'testtype')},
            },
        ),
        migrations.CreateModel(
            name='SectionBattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdata')),
            ],
            options={
                'unique_together': {('rollno', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectionB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtype', models.CharField(blank=True, max_length=30, null=True)),
                ('English', models.IntegerField(default=0)),
                ('Chemistry', models.IntegerField(default=0)),
                ('Urdu', models.IntegerField(default=0)),
                ('Physics', models.IntegerField(default=0)),
                ('SocialStudies', models.IntegerField(default=0)),
                ('Biology', models.IntegerField(default=0)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdata')),
            ],
            options={
                'unique_together': {('rollno', 'testtype')},
            },
        ),
        migrations.CreateModel(
            name='SectionAattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=15, null=True)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdata')),
            ],
            options={
                'unique_together': {('rollno', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectionA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtype', models.CharField(blank=True, max_length=30, null=True)),
                ('English', models.IntegerField(default=0)),
                ('Maths', models.IntegerField(default=0)),
                ('Urdu', models.IntegerField(default=0)),
                ('Chemistry', models.IntegerField(default=0)),
                ('SocialStudies', models.IntegerField(default=0)),
                ('Physics', models.IntegerField(default=0)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdata')),
            ],
            options={
                'unique_together': {('rollno', 'testtype')},
            },
        ),
    ]
