# Generated by Django 4.2.7 on 2023-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='rollNumber',
            field=models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
