# Generated by Django 4.2.7 on 2023-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_subjects_studentdata_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('SectionA', 'SectionA'), ('SectionB', 'SectionB'), ('SectionC', 'SectionC')], max_length=20)),
                ('lecture_title', models.CharField(max_length=255)),
                ('lecturer', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
            ],
            options={
                'unique_together': {('section', 'lecture_title')},
            },
        ),
    ]
