# Generated by Django 4.2.7 on 2023-12-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('section', 'lecture_title', 'day_of_week')},
        ),
    ]
