# Generated by Django 4.2.4 on 2023-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='testtype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
