# Generated by Django 4.2.7 on 2023-11-27 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('pre_engineering', 'Pre Engineering'), ('medical', 'Medical'), ('icom', 'I.Com'), ('yet_to_be_registered', 'Yet to be Registered')], default='yet_to_be_registered', max_length=40)),
                ('batch', models.IntegerField(default=2023, editable=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NAN', 'NAN')], default='NAN', max_length=3)),
                ('cnic', models.CharField(default='Not submitted yet', max_length=15)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(choices=[('pakistani', 'Pakistani'), ('foreign', 'Foreign')], default='Pakistani', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
