# Generated by Django 4.2.7 on 2023-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('ELECTRICAL', 'ELECTRICAL'), ('CIVIL', 'CIVIL'), ('yet_to_be_registered', 'Yet to be Registered')], default='yet_to_be_registered', max_length=40),
        ),
    ]
