# Generated by Django 4.2.7 on 2023-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'),
                                   ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NAN', 'NAN')], default='NAN', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='cnic',
            field=models.CharField(max_length=15, ),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('pre_engineering', 'Pre Engineering'), ('medical', 'Medical'), ('icom', 'I.Com'), (
                'yet_to_be_registered', 'Yet to be Registered')], default='yet_to_be_registered', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[(
                'pakistani', 'Pakistani'), ('foreign', 'Foreign')], default='Pakistani', max_length=15),
        ),
    ]
